development:
  adapter: mysql
  encoding: utf8
  database: weinkeller-ruby
  pool: 5
  username: weinkeller
  password: weinkeller2014ffhs
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: weinkeller-ruby
  pool: 5
  username: weinkeller
  password: weinkeller2014ffhs
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: weinkeller-ruby-prd
  pool: 5
  username: weinkeller
  password: weinkeller2014ffhs
  socket: /var/run/mysqld/mysqld.sock
